### PR TITLE
Update ru_ru.json

### PR DESCRIPTION
**Pull request by mpustovoi**
Updated ru_ru.json

### CODE REVIEW

**Comment by mpustovoi** [comment]
It would be nice if achievements were also translatable.

**Comment by mpustovoi** [comment]
I'll submit it myself later.

**Comment by Mikeatron-User** [comment]
I will add this in the next major update. :)

**Comment by mpustovoi** [comment]
If you're talking about translatable achievements, then I'm all for it!

**Comment by Mikeatron-User** [comment]
It will release with the 0.9 Update. I'll let you know when I implement it in the main branch so you can do proper translation for it.

**Comment by Mikeatron-User** [comment]
@mpustovoi Added Translate-able achievements in latest push, enjoy :)

**Pull request closed without merging**
